version: '3.8'
services:

  frontend:
    container_name: frontend_container
    build:
      context: .
      dockerfile: pccw-front/Dockerfile
    ports:
      - "3000:3000"   

  api:
    container_name: node_assignment
    restart: always
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - postgres_db
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules

  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pccw@example.com   
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}          
    ports:
      - "5050:80"   


volumes: 
 data: {}